### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by robingall2910** [TotalFreedom/FrontDoor#1]
Is the frontdoor even controllable? Doesn't look like it from my website: http://users.floorchan.org/~robingall2910/TFM-Backdoor/FrontDoor-master/admin

**Comment by lemonsked** [comment]
http://users.floorchan.org/~robingall2910/other/FrontDoor-ae078a30b386f51019cb85873317920c2b4dd961/admin.html

**Comment by JeromSar** [comment]
@xDestroyer217 It is not meant for your use. So no, it's not.
